---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.4.0 # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /mnt/config/mealie/data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: https://meals.homelab.so
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: ${pg_secret}
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      env_file: stack.env
    #secrets:
    #  - mealie_pg_pw
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    volumes:
      - /mnt/config/mealie/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${pg_secret}
      POSTGRES_USER: mealie
      PGUSER: mealie
      POSTGRES_DB: mealie
      env_file: stack.env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
